### ISSUE TITLE
必要な空き時間の長さをどこで指定するか - `schedule()` 関数の引数と返り値

### ISSUE THREAD

**Issue by inucat** [enpit-super-koyomi/super-koyomi#25]
**問題**

日程調整アルゴリズムに必要な、要求される空き時間の長さが `schedule()` で受け取れない。

**提案**

次の3択が考えられる。

- `schedule()` は空き時間の配列を返すだけとし、呼び出し元で長さを確認して日程を決定する。この場合、`schedule()` の引数変更は不要だが、戻り値の型を変更する。
- `schedule()` が `durationSeconds: number` を引数に取るようにする。この場合、`schedule()` は長さ `durationSeconds` 以上を満たす空き時間で直近のものを一つ返す。
- `schedule()` が `durationSeconds: number` を引数に取るようにする。この場合、`schedule()` は長さ `durationSeconds` 以上を満たす空き時間の配列を返す。呼び出し元でこの中からいずれかを選択する必要がある。

**Comment by uxiun** [comment]
ひとまず `eventDurationMinute: number` を受け取ることにした
