### ISSUE TITLE
デプロイ環境の日程調整で Internal Server Error が起こる

### ISSUE THREAD

**Issue by uxiun** [enpit-super-koyomi/super-koyomi#27]
**不具合の説明**
日時決定ボタンを押してもエラーが起きて Google Calendar に遷移しない。

**再現方法**
1. [調整ページ](https://app.superkoyomi.org/adjust)で日時決定ボタンを押す
2. 遷移しない
3. Consoleを開くと Internal Server Error が起きている

**期待される動作**
Google Calendar に遷移し、調整された日時が設定されている。

**スクリーンショット（あれば）**
![image](https://github.com/user-attachments/assets/efe1f224-af7f-444f-9ffb-d33305811d46)

**動作環境**
Windows11, Edge

**Comment by inucat** [comment]
Local環境では再現しませんでした。デプロイ環境だけで起こるようです。
@HosokawaR にVercel上で調査していただくのがよい？

**Comment by uxiun** [comment]
直ってましたね
