### ISSUE TITLE
全日の予定に関して、予定の開始・終了時刻が得られずschedule()が異常終了する

### ISSUE THREAD

**Issue by inucat** [enpit-super-koyomi/super-koyomi#36]
**不具合の説明**

Google Calendarで取得されるイベントに全日の予定が含まれると、日程調整時に開始時刻がnullとなる

**再現方法**

0｡　Google Calendarで全日の予定を調整開始時刻から一週間以内に入れる
1. /adjustを開く
2. 調整を始める
3. エラーが起こる

**期待される動作**

全日の予定に対しての挙動を定義して、適切に対処する。

**スクリーンショット（あれば）**

<img width="1280" alt="スクリーンショット 2024-10-23 18 39 09" src="https://github.com/user-attachments/assets/8ef03a2c-e592-465b-bb02-c1e95b520f8a">

**動作環境**
 - OS: macOS 12.7.6
 - ブラウザ: Firefox 131.0.3
 - 
**その他**

カレンダAPIの情報

https://developers.google.com/calendar/api/v3/reference/events?hl=ja

**Comment by uxiun** [comment]
全日の予定入れて試したけど問題ないみたい
